#!/usr/bin/env python3
"""Build installer/InstallCutscene.lua from the template and src/.

Each "{{path}}" string in the template is replaced with the file's contents
as a Lua long string. Run with --check to fail if the committed installer
is out of date.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "installer" / "InstallCutscene.template.lua"
OUTPUT = ROOT / "installer" / "InstallCutscene.lua"
PLACEHOLDER = re.compile(r'"\{\{([^}]+)\}\}"')
HEADER = (
    "-- GENERATED by tools/build_installer.py from installer/InstallCutscene.template.lua.\n"
    "-- Paste this whole file into the Roblox Studio Command Bar and press Enter.\n\n"
)


def long_string(text: str) -> str:
    level = 0
    while f"]{'=' * level}]" in text:
        level += 1
    eq = "=" * level
    # Lua drops the newline right after the opening bracket.
    return f"[{eq}[\n{text}]{eq}]"


def build() -> str:
    template = TEMPLATE.read_text(encoding="utf-8")

    def replace(match: re.Match) -> str:
        return long_string((ROOT / match.group(1)).read_text(encoding="utf-8"))

    body = PLACEHOLDER.sub(replace, template)
    # Drop the template's own "edit the template" banner (everything up to the
    # first blank line) in favour of the generated header.
    body = body.split("\n\n", 1)[1]
    return HEADER + body


def main() -> int:
    output = build()
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != output:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run tools/build_installer.py")
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
